<a href="https://colab.research.google.com/github/himanshu0108/Implementation_of_Basic_Tensorflow/blob/main/Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#One dimensional Tensor
#One dimensional tensor is a normal array structure which includes one set of values of the same data type.
import numpy as np
tensor_1d = np.array([3, 1, 4, 5])
print (tensor_1d)

[3 1 4 5]


In [2]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.13.0


In [3]:
#check indexing
print (tensor_1d[0])
print (tensor_1d[2])

3
4


In [4]:
#Two dimensional Tensors
#Sequence of arrays are used for creating “two dimensional tensors”.

#The creation of two-dimensional tensors is described below −
import numpy as np
tensor_2d = np.array([(1,2,3,4),(4,5,6,7),(8,9,10,11),(12,13,14,15)])
print(tensor_2d)


[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [5]:
#The specific elements of two dimensional tensors can be tracked with the help of row number and column number specified as index numbers.
tensor_2d[3][2]

14

In [6]:
#ensor Handling and Manipulations
import tensorflow as tf
import numpy as np

matrix1 = np.array([(2,2,2),(2,2,2),(2,2,2)],dtype = 'int32')
matrix2 = np.array([(1,1,1),(1,1,1),(1,1,1)],dtype = 'int32')
print (matrix1)
print (matrix2)

[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [7]:
matrix1 = tf.constant(matrix1)
matrix2 = tf.constant(matrix2)
print (matrix1)
print (matrix2)

tf.Tensor(
[[2 2 2]
 [2 2 2]
 [2 2 2]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]], shape=(3, 3), dtype=int32)


In [8]:
matrix_product = tf.matmul(matrix1, matrix2)
matrix_sum = tf.add(matrix1,matrix2)
print(matrix_product)
print(matrix_sum)


tf.Tensor(
[[6 6 6]
 [6 6 6]
 [6 6 6]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[3 3 3]
 [3 3 3]
 [3 3 3]], shape=(3, 3), dtype=int32)


In [9]:
matrix_3 = np.array([(2,7,2),(1,4,2),(9,0,2)],dtype = 'float32')
print (matrix_3)

[[2. 7. 2.]
 [1. 4. 2.]
 [9. 0. 2.]]


In [10]:
#matrix_det = tf.matrix_determinant(matrix_3) #is deprecated and revived as tf.linalg.det
matrix_det = tf.linalg.det(matrix_3)
print(matrix_det)

tf.Tensor(55.999992, shape=(), dtype=float32)
